# -*- coding: utf-8 -*-
"""Invisibility Cloak

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1513iDf4fzIGo6Mbot2JXA8wK1Z4VeT2h
"""

!pip install opencv-python
import cv2
from google.colab.patches import cv2_imshow
frontImg=cv2.imread("/content/bg.jpeg")
inpImg=cv2.imread("/content/cloak.jpeg")
frontImg=cv2.cvtColor(frontImg,cv2.COLOR_BGR2RGB)
print(f'backImgsize:{inpImg.shape}')
print(f'frontImgsize:{frontImg.shape}')
inpImg=cv2.resize(inpImg,(325,600))
frontImg=cv2.resize(frontImg,(325,600))
wi=inpImg.shape[1]
hi=inpImg.shape[0]
wif=inpImg.shape[1]
hif=frontImg.shape[0]
for i in range(hif):
  for j in range(wif):
    redF=frontImg[i,j,0]
    blueF=frontImg[i,j,1]
    greenF=frontImg[i,j,2]
    if not(redF<60 and greenF<185 and blueF>80):
      inpImg[i,j],frontImg[i,j]
      outImg=cv2.cvtColor(inpImg,cv2.COLOR_RGB2BGR)
cv2.imwrite("out.jpeg",outImg)
cv2_imshow(outImg)